project:
  type: book

book:
  title: "Guia_Rapida_MarckDown"
  author: "Tec. Sup. Christopher Jara"
  date: "28-10-2025"
  chapters:
    - index.qmd
    - 2_Guia_Rapida.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



